// overrides-derived.cjs.js — CommonJS
const DEPT_MAP = new Map([
  [`Antioquia`, `antioquia`],
  [`Atlantico`, `atlantico`],
  [`Bolivar`, `bolivar`],
  [`Boyaca`, `boyaca`],
  [`Caldas`, `caldas`],
  [`Caqueta`, `caqueta`],
  [`Casanare`, `casanare`],
  [`Cesar`, `cesar`],
  [`Cordoba`, `cordoba`],
  [`Cundinamarca`, `cundinamarca`],
  [`Huila`, `huila`],
  [`Magdalena`, `magdalena`],
  [`Meta`, `meta`],
  [`Narino`, `narino`],
  [`Quindio`, `quindio`],
  [`Risaralda`, `risaralda`],
  [`Santander`, `santander`],
  [`Tolima`, `tolima`],
  [`Valle Del Cauca`, `valle del cauca`],
]);

const CITY_MAP_BY_CITY_DEPT = new Map([
  [`Abejorral|Antioquia`, {"ciudad_canon": "abejorral", "departamento_para_ciudad": "antioquia", "clave": "abejorral__antioquia"}],
  [`Acacias|Meta`, {"ciudad_canon": "acacias", "departamento_para_ciudad": "meta", "clave": "acacias__meta"}],
  [`Aguachica|Cesar`, {"ciudad_canon": "aguachica", "departamento_para_ciudad": "cesar", "clave": "aguachica__cesar"}],
  [`Anapoima|Cundinamarca`, {"ciudad_canon": "anapoima", "departamento_para_ciudad": "cundinamarca", "clave": "anapoima__cundinamarca"}],
  [`Andalucia|Valle Del Cauca`, {"ciudad_canon": "andalucia", "departamento_para_ciudad": "valle del cauca", "clave": "andalucia__valle del cauca"}],
  [`Apartado|Antioquia`, {"ciudad_canon": "apartado", "departamento_para_ciudad": "antioquia", "clave": "apartado__antioquia"}],
  [`Armenia|Antioquia`, {"ciudad_canon": "armenia", "departamento_para_ciudad": "antioquia", "clave": "armenia__antioquia"}],
  [`Armenia|Quindio`, {"ciudad_canon": "armenia", "departamento_para_ciudad": "quindio", "clave": "armenia__quindio"}],
  [`Baranoa|Atlantico`, {"ciudad_canon": "baranoa", "departamento_para_ciudad": "atlantico", "clave": "baranoa__atlantico"}],
  [`Barbosa|Antioquia`, {"ciudad_canon": "barbosa", "departamento_para_ciudad": "antioquia", "clave": "barbosa__antioquia"}],
  [`Barrancabermeja|Santander`, {"ciudad_canon": "barrancabermeja", "departamento_para_ciudad": "santander", "clave": "barrancabermeja__santander"}],
  [`Barranquilla|Atlantico`, {"ciudad_canon": "barranquilla", "departamento_para_ciudad": "atlantico", "clave": "barranquilla__atlantico"}],
  [`Belen De Umbria|Risaralda`, {"ciudad_canon": "belen umbria", "departamento_para_ciudad": "risaralda", "clave": "belen umbria__risaralda"}],
  [`Bello|Antioquia`, {"ciudad_canon": "bello", "departamento_para_ciudad": "antioquia", "clave": "bello__antioquia"}],
  [`Bogota D.C.|Cundinamarca`, {"ciudad_canon": "bogota", "departamento_para_ciudad": "bogota dc", "clave": "bogota__bogota dc"}],
  [`Bucaramanga|Santander`, {"ciudad_canon": "bucaramanga", "departamento_para_ciudad": "santander", "clave": "bucaramanga__santander"}],
  [`Buenaventura|Valle Del Cauca`, {"ciudad_canon": "buenaventura", "departamento_para_ciudad": "valle del cauca", "clave": "buenaventura__valle del cauca"}],
  [`Bugalagrande|Valle Del Cauca`, {"ciudad_canon": "bugalagrande", "departamento_para_ciudad": "valle del cauca", "clave": "bugalagrande__valle del cauca"}],
  [`Caicedonia|Valle Del Cauca`, {"ciudad_canon": "caicedonia", "departamento_para_ciudad": "valle del cauca", "clave": "caicedonia__valle del cauca"}],
  [`Cajica|Cundinamarca`, {"ciudad_canon": "cajica", "departamento_para_ciudad": "cundinamarca", "clave": "cajica__cundinamarca"}],
  [`Caldas|Antioquia`, {"ciudad_canon": "caldas", "departamento_para_ciudad": "antioquia", "clave": "caldas__antioquia"}],
  [`Cali|Valle Del Cauca`, {"ciudad_canon": "cali", "departamento_para_ciudad": "valle del cauca", "clave": "cali__valle del cauca"}],
  [`Canasgordas|Antioquia`, {"ciudad_canon": "canasgordas", "departamento_para_ciudad": "antioquia", "clave": "canasgordas__antioquia"}],
  [`Candelaria|Valle Del Cauca`, {"ciudad_canon": "candelaria", "departamento_para_ciudad": "valle del cauca", "clave": "candelaria__valle del cauca"}],
  [`Carepa|Antioquia`, {"ciudad_canon": "carepa", "departamento_para_ciudad": "antioquia", "clave": "carepa__antioquia"}],
  [`Cartagena|Bolivar`, {"ciudad_canon": "cartagena", "departamento_para_ciudad": "bolivar", "clave": "cartagena__bolivar"}],
  [`Cartago|Valle Del Cauca`, {"ciudad_canon": "cartago", "departamento_para_ciudad": "valle del cauca", "clave": "cartago__valle del cauca"}],
  [`Caucasia|Antioquia`, {"ciudad_canon": "caucasia", "departamento_para_ciudad": "antioquia", "clave": "caucasia__antioquia"}],
  [`Chia|Cundinamarca`, {"ciudad_canon": "chia", "departamento_para_ciudad": "cundinamarca", "clave": "chia__cundinamarca"}],
  [`Cocorna|Antioquia`, {"ciudad_canon": "cocorna", "departamento_para_ciudad": "antioquia", "clave": "cocorna__antioquia"}],
  [`Cogua|Cundinamarca`, {"ciudad_canon": "cogua", "departamento_para_ciudad": "cundinamarca", "clave": "cogua__cundinamarca"}],
  [`Copacabana|Antioquia`, {"ciudad_canon": "copacabana", "departamento_para_ciudad": "antioquia", "clave": "copacabana__antioquia"}],
  [`Cota|Cundinamarca`, {"ciudad_canon": "cota", "departamento_para_ciudad": "cundinamarca", "clave": "cota__cundinamarca"}],
  [`Dagua|Valle Del Cauca`, {"ciudad_canon": "dagua", "departamento_para_ciudad": "valle del cauca", "clave": "dagua__valle del cauca"}],
  [`Dosquebradas|Risaralda`, {"ciudad_canon": "dosquebradas", "departamento_para_ciudad": "risaralda", "clave": "dosquebradas__risaralda"}],
  [`Duitama|Boyaca`, {"ciudad_canon": "duitama", "departamento_para_ciudad": "boyaca", "clave": "duitama__boyaca"}],
  [`El Carmen De Viboral|Antioquia`, {"ciudad_canon": "el carmen viboral", "departamento_para_ciudad": "antioquia", "clave": "el carmen viboral__antioquia"}],
  [`El Cerrito|Valle Del Cauca`, {"ciudad_canon": "el cerrito", "departamento_para_ciudad": "valle del cauca", "clave": "el cerrito__valle del cauca"}],
  [`El Colegio|Cundinamarca`, {"ciudad_canon": "el colegio", "departamento_para_ciudad": "cundinamarca", "clave": "el colegio__cundinamarca"}],
  [`El Rosal|Cundinamarca`, {"ciudad_canon": "el rosal", "departamento_para_ciudad": "cundinamarca", "clave": "el rosal__cundinamarca"}],
  [`El Santuario|Antioquia`, {"ciudad_canon": "el santuario", "departamento_para_ciudad": "antioquia", "clave": "el santuario__antioquia"}],
  [`Envigado|Antioquia`, {"ciudad_canon": "envigado", "departamento_para_ciudad": "antioquia", "clave": "envigado__antioquia"}],
  [`Espinal|Tolima`, {"ciudad_canon": "espinal", "departamento_para_ciudad": "tolima", "clave": "espinal__tolima"}],
  [`Facatativa|Cundinamarca`, {"ciudad_canon": "facatativa", "departamento_para_ciudad": "cundinamarca", "clave": "facatativa__cundinamarca"}],
  [`Florencia|Caqueta`, {"ciudad_canon": "florencia", "departamento_para_ciudad": "caqueta", "clave": "florencia__caqueta"}],
  [`Florida|Valle Del Cauca`, {"ciudad_canon": "florida", "departamento_para_ciudad": "valle del cauca", "clave": "florida__valle del cauca"}],
  [`Floridablanca|Santander`, {"ciudad_canon": "floridablanca", "departamento_para_ciudad": "santander", "clave": "floridablanca__santander"}],
  [`Fredonia|Antioquia`, {"ciudad_canon": "fredonia", "departamento_para_ciudad": "antioquia", "clave": "fredonia__antioquia"}],
  [`Funza|Cundinamarca`, {"ciudad_canon": "funza", "departamento_para_ciudad": "cundinamarca", "clave": "funza__cundinamarca"}],
  [`Fusagasuga|Cundinamarca`, {"ciudad_canon": "fusagasuga", "departamento_para_ciudad": "cundinamarca", "clave": "fusagasuga__cundinamarca"}],
  [`Gacheta|Cundinamarca`, {"ciudad_canon": "gacheta", "departamento_para_ciudad": "cundinamarca", "clave": "gacheta__cundinamarca"}],
  [`Galapa|Atlantico`, {"ciudad_canon": "galapa", "departamento_para_ciudad": "atlantico", "clave": "galapa__atlantico"}],
  [`Garzon|Huila`, {"ciudad_canon": "garzon", "departamento_para_ciudad": "huila", "clave": "garzon__huila"}],
  [`Ginebra|Valle Del Cauca`, {"ciudad_canon": "ginebra", "departamento_para_ciudad": "valle del cauca", "clave": "ginebra__valle del cauca"}],
  [`Girardot|Cundinamarca`, {"ciudad_canon": "girardot", "departamento_para_ciudad": "cundinamarca", "clave": "girardot__cundinamarca"}],
  [`Girardota|Antioquia`, {"ciudad_canon": "girardota", "departamento_para_ciudad": "antioquia", "clave": "girardota__antioquia"}],
  [`Giron|Santander`, {"ciudad_canon": "giron", "departamento_para_ciudad": "santander", "clave": "giron__santander"}],
  [`Granada|Antioquia`, {"ciudad_canon": "granada", "departamento_para_ciudad": "antioquia", "clave": "granada__antioquia"}],
  [`Guadalajara De Buga|Valle Del Cauca`, {"ciudad_canon": "guadalajara buga", "departamento_para_ciudad": "valle del cauca", "clave": "guadalajara buga__valle del cauca"}],
  [`Guadalupe|Santander`, {"ciudad_canon": "guadalupe", "departamento_para_ciudad": "santander", "clave": "guadalupe__santander"}],
  [`Guaduas|Cundinamarca`, {"ciudad_canon": "guaduas", "departamento_para_ciudad": "cundinamarca", "clave": "guaduas__cundinamarca"}],
  [`Guarne|Antioquia`, {"ciudad_canon": "guarne", "departamento_para_ciudad": "antioquia", "clave": "guarne__antioquia"}],
  [`Guasca|Cundinamarca`, {"ciudad_canon": "guasca", "departamento_para_ciudad": "cundinamarca", "clave": "guasca__cundinamarca"}],
  [`Ibague|Tolima`, {"ciudad_canon": "ibague", "departamento_para_ciudad": "tolima", "clave": "ibague__tolima"}],
  [`Itagui|Antioquia`, {"ciudad_canon": "itagui", "departamento_para_ciudad": "antioquia", "clave": "itagui__antioquia"}],
  [`Jamundi|Valle Del Cauca`, {"ciudad_canon": "jamundi", "departamento_para_ciudad": "valle del cauca", "clave": "jamundi__valle del cauca"}],
  [`La Calera|Cundinamarca`, {"ciudad_canon": "la calera", "departamento_para_ciudad": "cundinamarca", "clave": "la calera__cundinamarca"}],
  [`La Ceja|Antioquia`, {"ciudad_canon": "la ceja", "departamento_para_ciudad": "antioquia", "clave": "la ceja__antioquia"}],
  [`La Estrella|Antioquia`, {"ciudad_canon": "la estrella", "departamento_para_ciudad": "antioquia", "clave": "la estrella__antioquia"}],
  [`La Mesa|Cundinamarca`, {"ciudad_canon": "la mesa", "departamento_para_ciudad": "cundinamarca", "clave": "la mesa__cundinamarca"}],
  [`La Union|Valle Del Cauca`, {"ciudad_canon": "la union", "departamento_para_ciudad": "valle del cauca", "clave": "la union__valle del cauca"}],
  [`La Vega|Cundinamarca`, {"ciudad_canon": "la vega", "departamento_para_ciudad": "cundinamarca", "clave": "la vega__cundinamarca"}],
  [`Lebrija|Santander`, {"ciudad_canon": "lebrija", "departamento_para_ciudad": "santander", "clave": "lebrija__santander"}],
  [`Madrid|Cundinamarca`, {"ciudad_canon": "madrid", "departamento_para_ciudad": "cundinamarca", "clave": "madrid__cundinamarca"}],
  [`Malambo|Atlantico`, {"ciudad_canon": "malambo", "departamento_para_ciudad": "atlantico", "clave": "malambo__atlantico"}],
  [`Manizales|Caldas`, {"ciudad_canon": "manizales", "departamento_para_ciudad": "caldas", "clave": "manizales__caldas"}],
  [`Marinilla|Antioquia`, {"ciudad_canon": "marinilla", "departamento_para_ciudad": "antioquia", "clave": "marinilla__antioquia"}],
  [`Medellin|Antioquia`, {"ciudad_canon": "medellin", "departamento_para_ciudad": "antioquia", "clave": "medellin__antioquia"}],
  [`Monteria|Cordoba`, {"ciudad_canon": "monteria", "departamento_para_ciudad": "cordoba", "clave": "monteria__cordoba"}],
  [`Mosquera|Cundinamarca`, {"ciudad_canon": "mosquera", "departamento_para_ciudad": "cundinamarca", "clave": "mosquera__cundinamarca"}],
  [`Mutata|Antioquia`, {"ciudad_canon": "mutata", "departamento_para_ciudad": "antioquia", "clave": "mutata__antioquia"}],
  [`Neiva|Huila`, {"ciudad_canon": "neiva", "departamento_para_ciudad": "huila", "clave": "neiva__huila"}],
  [`Pacho|Cundinamarca`, {"ciudad_canon": "pacho", "departamento_para_ciudad": "cundinamarca", "clave": "pacho__cundinamarca"}],
  [`Palmar De Varela|Atlantico`, {"ciudad_canon": "palmar varela", "departamento_para_ciudad": "atlantico", "clave": "palmar varela__atlantico"}],
  [`Palmira|Valle Del Cauca`, {"ciudad_canon": "palmira", "departamento_para_ciudad": "valle del cauca", "clave": "palmira__valle del cauca"}],
  [`Pasto|Narino`, {"ciudad_canon": "pasto", "departamento_para_ciudad": "narino", "clave": "pasto__narino"}],
  [`Penol|Antioquia`, {"ciudad_canon": "penol", "departamento_para_ciudad": "antioquia", "clave": "penol__antioquia"}],
  [`Pereira|Risaralda`, {"ciudad_canon": "pereira", "departamento_para_ciudad": "risaralda", "clave": "pereira__risaralda"}],
  [`Piedecuesta|Santander`, {"ciudad_canon": "piedecuesta", "departamento_para_ciudad": "santander", "clave": "piedecuesta__santander"}],
  [`Pitalito|Huila`, {"ciudad_canon": "pitalito", "departamento_para_ciudad": "huila", "clave": "pitalito__huila"}],
  [`Polonuevo|Atlantico`, {"ciudad_canon": "polonuevo", "departamento_para_ciudad": "atlantico", "clave": "polonuevo__atlantico"}],
  [`Ponedera|Atlantico`, {"ciudad_canon": "ponedera", "departamento_para_ciudad": "atlantico", "clave": "ponedera__atlantico"}],
  [`Pradera|Valle Del Cauca`, {"ciudad_canon": "pradera", "departamento_para_ciudad": "valle del cauca", "clave": "pradera__valle del cauca"}],
  [`Puerto Colombia|Atlantico`, {"ciudad_canon": "puerto colombia", "departamento_para_ciudad": "atlantico", "clave": "puerto colombia__atlantico"}],
  [`Ricaurte|Cundinamarca`, {"ciudad_canon": "ricaurte", "departamento_para_ciudad": "cundinamarca", "clave": "ricaurte__cundinamarca"}],
  [`Rionegro|Antioquia`, {"ciudad_canon": "rionegro", "departamento_para_ciudad": "antioquia", "clave": "rionegro__antioquia"}],
  [`Rionegro|Santander`, {"ciudad_canon": "rionegro", "departamento_para_ciudad": "santander", "clave": "rionegro__santander"}],
  [`Sabana De Torres|Santander`, {"ciudad_canon": "sabana torres", "departamento_para_ciudad": "santander", "clave": "sabana torres__santander"}],
  [`Sabaneta|Antioquia`, {"ciudad_canon": "sabaneta", "departamento_para_ciudad": "antioquia", "clave": "sabaneta__antioquia"}],
  [`San Agustin|Huila`, {"ciudad_canon": "san agustin", "departamento_para_ciudad": "huila", "clave": "san agustin__huila"}],
  [`San Gil|Santander`, {"ciudad_canon": "san gil", "departamento_para_ciudad": "santander", "clave": "san gil__santander"}],
  [`San Juan De Rio Seco|Cundinamarca`, {"ciudad_canon": "san juan rio seco", "departamento_para_ciudad": "cundinamarca", "clave": "san juan rio seco__cundinamarca"}],
  [`San Pedro De Uraba|Antioquia`, {"ciudad_canon": "san pedro uraba", "departamento_para_ciudad": "antioquia", "clave": "san pedro uraba__antioquia"}],
  [`San Vicente De Chucuri|Santander`, {"ciudad_canon": "san vicente chucuri", "departamento_para_ciudad": "santander", "clave": "san vicente chucuri__santander"}],
  [`Santa Marta|Magdalena`, {"ciudad_canon": "santa marta", "departamento_para_ciudad": "magdalena", "clave": "santa marta__magdalena"}],
  [`Santa Rosa De Cabal|Risaralda`, {"ciudad_canon": "santa rosa de cabal", "departamento_para_ciudad": "risaralda", "clave": "santa rosa de cabal__risaralda"}],
  [`Santo Tomas|Atlantico`, {"ciudad_canon": "santo tomas", "departamento_para_ciudad": "atlantico", "clave": "santo tomas__atlantico"}],
  [`Segovia|Antioquia`, {"ciudad_canon": "segovia", "departamento_para_ciudad": "antioquia", "clave": "segovia__antioquia"}],
  [`Sevilla|Valle Del Cauca`, {"ciudad_canon": "sevilla", "departamento_para_ciudad": "valle del cauca", "clave": "sevilla__valle del cauca"}],
  [`Sibate|Cundinamarca`, {"ciudad_canon": "sibate", "departamento_para_ciudad": "cundinamarca", "clave": "sibate__cundinamarca"}],
  [`Silvania|Cundinamarca`, {"ciudad_canon": "silvania", "departamento_para_ciudad": "cundinamarca", "clave": "silvania__cundinamarca"}],
  [`Soacha|Cundinamarca`, {"ciudad_canon": "soacha", "departamento_para_ciudad": "cundinamarca", "clave": "soacha__cundinamarca"}],
  [`Socorro|Santander`, {"ciudad_canon": "socorro", "departamento_para_ciudad": "santander", "clave": "socorro__santander"}],
  [`Sogamoso|Boyaca`, {"ciudad_canon": "sogamoso", "departamento_para_ciudad": "boyaca", "clave": "sogamoso__boyaca"}],
  [`Soledad|Atlantico`, {"ciudad_canon": "soledad", "departamento_para_ciudad": "atlantico", "clave": "soledad__atlantico"}],
  [`Sopo|Cundinamarca`, {"ciudad_canon": "sopo", "departamento_para_ciudad": "cundinamarca", "clave": "sopo__cundinamarca"}],
  [`Suan|Atlantico`, {"ciudad_canon": "suan", "departamento_para_ciudad": "atlantico", "clave": "suan__atlantico"}],
  [`Tabio|Cundinamarca`, {"ciudad_canon": "tabio", "departamento_para_ciudad": "cundinamarca", "clave": "tabio__cundinamarca"}],
  [`Tamesis|Antioquia`, {"ciudad_canon": "tamesis", "departamento_para_ciudad": "antioquia", "clave": "tamesis__antioquia"}],
  [`Tenjo|Cundinamarca`, {"ciudad_canon": "tenjo", "departamento_para_ciudad": "cundinamarca", "clave": "tenjo__cundinamarca"}],
  [`Tocancipa|Cundinamarca`, {"ciudad_canon": "tocancipa", "departamento_para_ciudad": "cundinamarca", "clave": "tocancipa__cundinamarca"}],
  [`Trujillo|Valle Del Cauca`, {"ciudad_canon": "trujillo", "departamento_para_ciudad": "valle del cauca", "clave": "trujillo__valle del cauca"}],
  [`Tulua|Valle Del Cauca`, {"ciudad_canon": "tulua", "departamento_para_ciudad": "valle del cauca", "clave": "tulua__valle del cauca"}],
  [`San Andres De Tumaco|Narino`, {"ciudad_canon": "tumaco", "departamento_para_ciudad": "narino", "clave": "tumaco__narino"}],
  [`Tunja|Boyaca`, {"ciudad_canon": "tunja", "departamento_para_ciudad": "boyaca", "clave": "tunja__boyaca"}],
  [`Vijes|Valle Del Cauca`, {"ciudad_canon": "vijes", "departamento_para_ciudad": "valle del cauca", "clave": "vijes__valle del cauca"}],
  [`Villa De San Diego De Ubate|Cundinamarca`, {"ciudad_canon": "villa san diego ubate", "departamento_para_ciudad": "cundinamarca", "clave": "villa san diego ubate__cundinamarca"}],
  [`Villavicencio|Meta`, {"ciudad_canon": "villavicencio", "departamento_para_ciudad": "meta", "clave": "villavicencio__meta"}],
  [`Villeta|Cundinamarca`, {"ciudad_canon": "villeta", "departamento_para_ciudad": "cundinamarca", "clave": "villeta__cundinamarca"}],
  [`Viota|Cundinamarca`, {"ciudad_canon": "viota", "departamento_para_ciudad": "cundinamarca", "clave": "viota__cundinamarca"}],
  [`Yarumal|Antioquia`, {"ciudad_canon": "yarumal", "departamento_para_ciudad": "antioquia", "clave": "yarumal__antioquia"}],
  [`Yondo|Antioquia`, {"ciudad_canon": "yondo", "departamento_para_ciudad": "antioquia", "clave": "yondo__antioquia"}],
  [`Yopal|Casanare`, {"ciudad_canon": "yopal", "departamento_para_ciudad": "casanare", "clave": "yopal__casanare"}],
  [`Yumbo|Valle Del Cauca`, {"ciudad_canon": "yumbo", "departamento_para_ciudad": "valle del cauca", "clave": "yumbo__valle del cauca"}],
  [`Zarzal|Valle Del Cauca`, {"ciudad_canon": "zarzal", "departamento_para_ciudad": "valle del cauca", "clave": "zarzal__valle del cauca"}],
  [`Zipaquira|Cundinamarca`, {"ciudad_canon": "zipaquira", "departamento_para_ciudad": "cundinamarca", "clave": "zipaquira__cundinamarca"}],
]);

const CITY_MAP_BY_CITY_ONLY = new Map([
  [`Abejorral`, {"ciudad_canon": "abejorral", "departamento_para_ciudad": "antioquia", "clave": "abejorral__antioquia"}],
  [`Acacias`, {"ciudad_canon": "acacias", "departamento_para_ciudad": "meta", "clave": "acacias__meta"}],
  [`Aguachica`, {"ciudad_canon": "aguachica", "departamento_para_ciudad": "cesar", "clave": "aguachica__cesar"}],
  [`Anapoima`, {"ciudad_canon": "anapoima", "departamento_para_ciudad": "cundinamarca", "clave": "anapoima__cundinamarca"}],
  [`Andalucia`, {"ciudad_canon": "andalucia", "departamento_para_ciudad": "valle del cauca", "clave": "andalucia__valle del cauca"}],
  [`Apartado`, {"ciudad_canon": "apartado", "departamento_para_ciudad": "antioquia", "clave": "apartado__antioquia"}],
  [`Armenia`, {"ciudad_canon": "armenia", "departamento_para_ciudad": "antioquia", "clave": "armenia__antioquia"}],
  [`Baranoa`, {"ciudad_canon": "baranoa", "departamento_para_ciudad": "atlantico", "clave": "baranoa__atlantico"}],
  [`Barbosa`, {"ciudad_canon": "barbosa", "departamento_para_ciudad": "antioquia", "clave": "barbosa__antioquia"}],
  [`Barrancabermeja`, {"ciudad_canon": "barrancabermeja", "departamento_para_ciudad": "santander", "clave": "barrancabermeja__santander"}],
  [`Barranquilla`, {"ciudad_canon": "barranquilla", "departamento_para_ciudad": "atlantico", "clave": "barranquilla__atlantico"}],
  [`Belen De Umbria`, {"ciudad_canon": "belen umbria", "departamento_para_ciudad": "risaralda", "clave": "belen umbria__risaralda"}],
  [`Bello`, {"ciudad_canon": "bello", "departamento_para_ciudad": "antioquia", "clave": "bello__antioquia"}],
  [`Bogota D.C.`, {"ciudad_canon": "bogota", "departamento_para_ciudad": "bogota dc", "clave": "bogota__bogota dc"}],
  [`Bucaramanga`, {"ciudad_canon": "bucaramanga", "departamento_para_ciudad": "santander", "clave": "bucaramanga__santander"}],
  [`Buenaventura`, {"ciudad_canon": "buenaventura", "departamento_para_ciudad": "valle del cauca", "clave": "buenaventura__valle del cauca"}],
  [`Bugalagrande`, {"ciudad_canon": "bugalagrande", "departamento_para_ciudad": "valle del cauca", "clave": "bugalagrande__valle del cauca"}],
  [`Caicedonia`, {"ciudad_canon": "caicedonia", "departamento_para_ciudad": "valle del cauca", "clave": "caicedonia__valle del cauca"}],
  [`Cajica`, {"ciudad_canon": "cajica", "departamento_para_ciudad": "cundinamarca", "clave": "cajica__cundinamarca"}],
  [`Caldas`, {"ciudad_canon": "caldas", "departamento_para_ciudad": "antioquia", "clave": "caldas__antioquia"}],
  [`Cali`, {"ciudad_canon": "cali", "departamento_para_ciudad": "valle del cauca", "clave": "cali__valle del cauca"}],
  [`Canasgordas`, {"ciudad_canon": "canasgordas", "departamento_para_ciudad": "antioquia", "clave": "canasgordas__antioquia"}],
  [`Candelaria`, {"ciudad_canon": "candelaria", "departamento_para_ciudad": "valle del cauca", "clave": "candelaria__valle del cauca"}],
  [`Carepa`, {"ciudad_canon": "carepa", "departamento_para_ciudad": "antioquia", "clave": "carepa__antioquia"}],
  [`Cartagena`, {"ciudad_canon": "cartagena", "departamento_para_ciudad": "bolivar", "clave": "cartagena__bolivar"}],
  [`Cartago`, {"ciudad_canon": "cartago", "departamento_para_ciudad": "valle del cauca", "clave": "cartago__valle del cauca"}],
  [`Caucasia`, {"ciudad_canon": "caucasia", "departamento_para_ciudad": "antioquia", "clave": "caucasia__antioquia"}],
  [`Chia`, {"ciudad_canon": "chia", "departamento_para_ciudad": "cundinamarca", "clave": "chia__cundinamarca"}],
  [`Cocorna`, {"ciudad_canon": "cocorna", "departamento_para_ciudad": "antioquia", "clave": "cocorna__antioquia"}],
  [`Cogua`, {"ciudad_canon": "cogua", "departamento_para_ciudad": "cundinamarca", "clave": "cogua__cundinamarca"}],
  [`Copacabana`, {"ciudad_canon": "copacabana", "departamento_para_ciudad": "antioquia", "clave": "copacabana__antioquia"}],
  [`Cota`, {"ciudad_canon": "cota", "departamento_para_ciudad": "cundinamarca", "clave": "cota__cundinamarca"}],
  [`Dagua`, {"ciudad_canon": "dagua", "departamento_para_ciudad": "valle del cauca", "clave": "dagua__valle del cauca"}],
  [`Dosquebradas`, {"ciudad_canon": "dosquebradas", "departamento_para_ciudad": "risaralda", "clave": "dosquebradas__risaralda"}],
  [`Duitama`, {"ciudad_canon": "duitama", "departamento_para_ciudad": "boyaca", "clave": "duitama__boyaca"}],
  [`El Carmen De Viboral`, {"ciudad_canon": "el carmen viboral", "departamento_para_ciudad": "antioquia", "clave": "el carmen viboral__antioquia"}],
  [`El Cerrito`, {"ciudad_canon": "el cerrito", "departamento_para_ciudad": "valle del cauca", "clave": "el cerrito__valle del cauca"}],
  [`El Colegio`, {"ciudad_canon": "el colegio", "departamento_para_ciudad": "cundinamarca", "clave": "el colegio__cundinamarca"}],
  [`El Rosal`, {"ciudad_canon": "el rosal", "departamento_para_ciudad": "cundinamarca", "clave": "el rosal__cundinamarca"}],
  [`El Santuario`, {"ciudad_canon": "el santuario", "departamento_para_ciudad": "antioquia", "clave": "el santuario__antioquia"}],
  [`Envigado`, {"ciudad_canon": "envigado", "departamento_para_ciudad": "antioquia", "clave": "envigado__antioquia"}],
  [`Espinal`, {"ciudad_canon": "espinal", "departamento_para_ciudad": "tolima", "clave": "espinal__tolima"}],
  [`Facatativa`, {"ciudad_canon": "facatativa", "departamento_para_ciudad": "cundinamarca", "clave": "facatativa__cundinamarca"}],
  [`Florencia`, {"ciudad_canon": "florencia", "departamento_para_ciudad": "caqueta", "clave": "florencia__caqueta"}],
  [`Florida`, {"ciudad_canon": "florida", "departamento_para_ciudad": "valle del cauca", "clave": "florida__valle del cauca"}],
  [`Floridablanca`, {"ciudad_canon": "floridablanca", "departamento_para_ciudad": "santander", "clave": "floridablanca__santander"}],
  [`Fredonia`, {"ciudad_canon": "fredonia", "departamento_para_ciudad": "antioquia", "clave": "fredonia__antioquia"}],
  [`Funza`, {"ciudad_canon": "funza", "departamento_para_ciudad": "cundinamarca", "clave": "funza__cundinamarca"}],
  [`Fusagasuga`, {"ciudad_canon": "fusagasuga", "departamento_para_ciudad": "cundinamarca", "clave": "fusagasuga__cundinamarca"}],
  [`Gacheta`, {"ciudad_canon": "gacheta", "departamento_para_ciudad": "cundinamarca", "clave": "gacheta__cundinamarca"}],
  [`Galapa`, {"ciudad_canon": "galapa", "departamento_para_ciudad": "atlantico", "clave": "galapa__atlantico"}],
  [`Garzon`, {"ciudad_canon": "garzon", "departamento_para_ciudad": "huila", "clave": "garzon__huila"}],
  [`Ginebra`, {"ciudad_canon": "ginebra", "departamento_para_ciudad": "valle del cauca", "clave": "ginebra__valle del cauca"}],
  [`Girardot`, {"ciudad_canon": "girardot", "departamento_para_ciudad": "cundinamarca", "clave": "girardot__cundinamarca"}],
  [`Girardota`, {"ciudad_canon": "girardota", "departamento_para_ciudad": "antioquia", "clave": "girardota__antioquia"}],
  [`Giron`, {"ciudad_canon": "giron", "departamento_para_ciudad": "santander", "clave": "giron__santander"}],
  [`Granada`, {"ciudad_canon": "granada", "departamento_para_ciudad": "antioquia", "clave": "granada__antioquia"}],
  [`Guadalajara De Buga`, {"ciudad_canon": "guadalajara buga", "departamento_para_ciudad": "valle del cauca", "clave": "guadalajara buga__valle del cauca"}],
  [`Guadalupe`, {"ciudad_canon": "guadalupe", "departamento_para_ciudad": "santander", "clave": "guadalupe__santander"}],
  [`Guaduas`, {"ciudad_canon": "guaduas", "departamento_para_ciudad": "cundinamarca", "clave": "guaduas__cundinamarca"}],
  [`Guarne`, {"ciudad_canon": "guarne", "departamento_para_ciudad": "antioquia", "clave": "guarne__antioquia"}],
  [`Guasca`, {"ciudad_canon": "guasca", "departamento_para_ciudad": "cundinamarca", "clave": "guasca__cundinamarca"}],
  [`Ibague`, {"ciudad_canon": "ibague", "departamento_para_ciudad": "tolima", "clave": "ibague__tolima"}],
  [`Itagui`, {"ciudad_canon": "itagui", "departamento_para_ciudad": "antioquia", "clave": "itagui__antioquia"}],
  [`Jamundi`, {"ciudad_canon": "jamundi", "departamento_para_ciudad": "valle del cauca", "clave": "jamundi__valle del cauca"}],
  [`La Calera`, {"ciudad_canon": "la calera", "departamento_para_ciudad": "cundinamarca", "clave": "la calera__cundinamarca"}],
  [`La Ceja`, {"ciudad_canon": "la ceja", "departamento_para_ciudad": "antioquia", "clave": "la ceja__antioquia"}],
  [`La Estrella`, {"ciudad_canon": "la estrella", "departamento_para_ciudad": "antioquia", "clave": "la estrella__antioquia"}],
  [`La Mesa`, {"ciudad_canon": "la mesa", "departamento_para_ciudad": "cundinamarca", "clave": "la mesa__cundinamarca"}],
  [`La Union`, {"ciudad_canon": "la union", "departamento_para_ciudad": "valle del cauca", "clave": "la union__valle del cauca"}],
  [`La Vega`, {"ciudad_canon": "la vega", "departamento_para_ciudad": "cundinamarca", "clave": "la vega__cundinamarca"}],
  [`Lebrija`, {"ciudad_canon": "lebrija", "departamento_para_ciudad": "santander", "clave": "lebrija__santander"}],
  [`Madrid`, {"ciudad_canon": "madrid", "departamento_para_ciudad": "cundinamarca", "clave": "madrid__cundinamarca"}],
  [`Malambo`, {"ciudad_canon": "malambo", "departamento_para_ciudad": "atlantico", "clave": "malambo__atlantico"}],
  [`Manizales`, {"ciudad_canon": "manizales", "departamento_para_ciudad": "caldas", "clave": "manizales__caldas"}],
  [`Marinilla`, {"ciudad_canon": "marinilla", "departamento_para_ciudad": "antioquia", "clave": "marinilla__antioquia"}],
  [`Medellin`, {"ciudad_canon": "medellin", "departamento_para_ciudad": "antioquia", "clave": "medellin__antioquia"}],
  [`Monteria`, {"ciudad_canon": "monteria", "departamento_para_ciudad": "cordoba", "clave": "monteria__cordoba"}],
  [`Mosquera`, {"ciudad_canon": "mosquera", "departamento_para_ciudad": "cundinamarca", "clave": "mosquera__cundinamarca"}],
  [`Mutata`, {"ciudad_canon": "mutata", "departamento_para_ciudad": "antioquia", "clave": "mutata__antioquia"}],
  [`Neiva`, {"ciudad_canon": "neiva", "departamento_para_ciudad": "huila", "clave": "neiva__huila"}],
  [`Pacho`, {"ciudad_canon": "pacho", "departamento_para_ciudad": "cundinamarca", "clave": "pacho__cundinamarca"}],
  [`Palmar De Varela`, {"ciudad_canon": "palmar varela", "departamento_para_ciudad": "atlantico", "clave": "palmar varela__atlantico"}],
  [`Palmira`, {"ciudad_canon": "palmira", "departamento_para_ciudad": "valle del cauca", "clave": "palmira__valle del cauca"}],
  [`Pasto`, {"ciudad_canon": "pasto", "departamento_para_ciudad": "narino", "clave": "pasto__narino"}],
  [`Penol`, {"ciudad_canon": "penol", "departamento_para_ciudad": "antioquia", "clave": "penol__antioquia"}],
  [`Pereira`, {"ciudad_canon": "pereira", "departamento_para_ciudad": "risaralda", "clave": "pereira__risaralda"}],
  [`Piedecuesta`, {"ciudad_canon": "piedecuesta", "departamento_para_ciudad": "santander", "clave": "piedecuesta__santander"}],
  [`Pitalito`, {"ciudad_canon": "pitalito", "departamento_para_ciudad": "huila", "clave": "pitalito__huila"}],
  [`Polonuevo`, {"ciudad_canon": "polonuevo", "departamento_para_ciudad": "atlantico", "clave": "polonuevo__atlantico"}],
  [`Ponedera`, {"ciudad_canon": "ponedera", "departamento_para_ciudad": "atlantico", "clave": "ponedera__atlantico"}],
  [`Pradera`, {"ciudad_canon": "pradera", "departamento_para_ciudad": "valle del cauca", "clave": "pradera__valle del cauca"}],
  [`Puerto Colombia`, {"ciudad_canon": "puerto colombia", "departamento_para_ciudad": "atlantico", "clave": "puerto colombia__atlantico"}],
  [`Ricaurte`, {"ciudad_canon": "ricaurte", "departamento_para_ciudad": "cundinamarca", "clave": "ricaurte__cundinamarca"}],
  [`Rionegro`, {"ciudad_canon": "rionegro", "departamento_para_ciudad": "antioquia", "clave": "rionegro__antioquia"}],
  [`Sabana De Torres`, {"ciudad_canon": "sabana torres", "departamento_para_ciudad": "santander", "clave": "sabana torres__santander"}],
  [`Sabaneta`, {"ciudad_canon": "sabaneta", "departamento_para_ciudad": "antioquia", "clave": "sabaneta__antioquia"}],
  [`San Agustin`, {"ciudad_canon": "san agustin", "departamento_para_ciudad": "huila", "clave": "san agustin__huila"}],
  [`San Gil`, {"ciudad_canon": "san gil", "departamento_para_ciudad": "santander", "clave": "san gil__santander"}],
  [`San Juan De Rio Seco`, {"ciudad_canon": "san juan rio seco", "departamento_para_ciudad": "cundinamarca", "clave": "san juan rio seco__cundinamarca"}],
  [`San Pedro De Uraba`, {"ciudad_canon": "san pedro uraba", "departamento_para_ciudad": "antioquia", "clave": "san pedro uraba__antioquia"}],
  [`San Vicente De Chucuri`, {"ciudad_canon": "san vicente chucuri", "departamento_para_ciudad": "santander", "clave": "san vicente chucuri__santander"}],
  [`Santa Marta`, {"ciudad_canon": "santa marta", "departamento_para_ciudad": "magdalena", "clave": "santa marta__magdalena"}],
  [`Santa Rosa De Cabal`, {"ciudad_canon": "santa rosa de cabal", "departamento_para_ciudad": "risaralda", "clave": "santa rosa de cabal__risaralda"}],
  [`Santo Tomas`, {"ciudad_canon": "santo tomas", "departamento_para_ciudad": "atlantico", "clave": "santo tomas__atlantico"}],
  [`Segovia`, {"ciudad_canon": "segovia", "departamento_para_ciudad": "antioquia", "clave": "segovia__antioquia"}],
  [`Sevilla`, {"ciudad_canon": "sevilla", "departamento_para_ciudad": "valle del cauca", "clave": "sevilla__valle del cauca"}],
  [`Sibate`, {"ciudad_canon": "sibate", "departamento_para_ciudad": "cundinamarca", "clave": "sibate__cundinamarca"}],
  [`Silvania`, {"ciudad_canon": "silvania", "departamento_para_ciudad": "cundinamarca", "clave": "silvania__cundinamarca"}],
  [`Soacha`, {"ciudad_canon": "soacha", "departamento_para_ciudad": "cundinamarca", "clave": "soacha__cundinamarca"}],
  [`Socorro`, {"ciudad_canon": "socorro", "departamento_para_ciudad": "santander", "clave": "socorro__santander"}],
  [`Sogamoso`, {"ciudad_canon": "sogamoso", "departamento_para_ciudad": "boyaca", "clave": "sogamoso__boyaca"}],
  [`Soledad`, {"ciudad_canon": "soledad", "departamento_para_ciudad": "atlantico", "clave": "soledad__atlantico"}],
  [`Sopo`, {"ciudad_canon": "sopo", "departamento_para_ciudad": "cundinamarca", "clave": "sopo__cundinamarca"}],
  [`Suan`, {"ciudad_canon": "suan", "departamento_para_ciudad": "atlantico", "clave": "suan__atlantico"}],
  [`Tabio`, {"ciudad_canon": "tabio", "departamento_para_ciudad": "cundinamarca", "clave": "tabio__cundinamarca"}],
  [`Tamesis`, {"ciudad_canon": "tamesis", "departamento_para_ciudad": "antioquia", "clave": "tamesis__antioquia"}],
  [`Tenjo`, {"ciudad_canon": "tenjo", "departamento_para_ciudad": "cundinamarca", "clave": "tenjo__cundinamarca"}],
  [`Tocancipa`, {"ciudad_canon": "tocancipa", "departamento_para_ciudad": "cundinamarca", "clave": "tocancipa__cundinamarca"}],
  [`Trujillo`, {"ciudad_canon": "trujillo", "departamento_para_ciudad": "valle del cauca", "clave": "trujillo__valle del cauca"}],
  [`Tulua`, {"ciudad_canon": "tulua", "departamento_para_ciudad": "valle del cauca", "clave": "tulua__valle del cauca"}],
  [`San Andres De Tumaco`, {"ciudad_canon": "tumaco", "departamento_para_ciudad": "narino", "clave": "tumaco__narino"}],
  [`Tunja`, {"ciudad_canon": "tunja", "departamento_para_ciudad": "boyaca", "clave": "tunja__boyaca"}],
  [`Vijes`, {"ciudad_canon": "vijes", "departamento_para_ciudad": "valle del cauca", "clave": "vijes__valle del cauca"}],
  [`Villa De San Diego De Ubate`, {"ciudad_canon": "villa san diego ubate", "departamento_para_ciudad": "cundinamarca", "clave": "villa san diego ubate__cundinamarca"}],
  [`Villavicencio`, {"ciudad_canon": "villavicencio", "departamento_para_ciudad": "meta", "clave": "villavicencio__meta"}],
  [`Villeta`, {"ciudad_canon": "villeta", "departamento_para_ciudad": "cundinamarca", "clave": "villeta__cundinamarca"}],
  [`Viota`, {"ciudad_canon": "viota", "departamento_para_ciudad": "cundinamarca", "clave": "viota__cundinamarca"}],
  [`Yarumal`, {"ciudad_canon": "yarumal", "departamento_para_ciudad": "antioquia", "clave": "yarumal__antioquia"}],
  [`Yondo`, {"ciudad_canon": "yondo", "departamento_para_ciudad": "antioquia", "clave": "yondo__antioquia"}],
  [`Yopal`, {"ciudad_canon": "yopal", "departamento_para_ciudad": "casanare", "clave": "yopal__casanare"}],
  [`Yumbo`, {"ciudad_canon": "yumbo", "departamento_para_ciudad": "valle del cauca", "clave": "yumbo__valle del cauca"}],
  [`Zarzal`, {"ciudad_canon": "zarzal", "departamento_para_ciudad": "valle del cauca", "clave": "zarzal__valle del cauca"}],
  [`Zipaquira`, {"ciudad_canon": "zipaquira", "departamento_para_ciudad": "cundinamarca", "clave": "zipaquira__cundinamarca"}],
]);


function canonDeptStrict(canonBase, softClean, raw) {
  const kd = canonBase(softClean(raw));
  return DEPT_MAP.get(raw) || DEPT_MAP.get(kd) || kd;
}
function canonCityStrict(canonBase, softClean, cityRaw, deptRaw) {
  const kc = canonBase(softClean(cityRaw));
  const kd = canonBase(softClean(deptRaw));
  const rec = CITY_MAP_BY_CITY_DEPT.get(`${cityRaw}|${deptRaw}`)
         || CITY_MAP_BY_CITY_DEPT.get(`${kc}|${kd}`)
         || CITY_MAP_BY_CITY_ONLY.get(cityRaw)
         || CITY_MAP_BY_CITY_ONLY.get(kc);
  if (!rec) {
    const d = kd === 'bogota' || kd === 'bogota d c' || kd === 'bogota dc' ? 'bogota dc' : kd;
    return { ciudad_canon: kc, departamento_para_ciudad: d, clave: kc ? `${kc}__${d}` : "" };
  }
  return rec;
}
module.exports = { DEPT_MAP, CITY_MAP_BY_CITY_DEPT, CITY_MAP_BY_CITY_ONLY, canonDeptStrict, canonCityStrict };
